import Link from "next/link";

export default function DocsPage() {
  return <main className="docs-page">
    <nav className="case-nav"><Link href="/" className="wordmark"><span>✦</span> Faultline</Link><div><Link href="/dashboard">Workspace</Link><Link href="/evidence">Evidence</Link></div></nav>
    <header><span>SIMPLE GUIDE</span><h1>Faultline,<br />explained for anyone.</h1><p>You do not need to be an engineer to understand what the system sees, what it tests, and what it can honestly prove.</p></header>
    <section><article><b>01</b><div><h2>Why does Faultline exist?</h2><p>When a digital service breaks, teams often blame the loudest alert or the newest change. That first guess can be wrong. Faultline helps the team test the guess before acting on it.</p></div></article><article><b>02</b><div><h2>What does it watch today?</h2><p>Faultline checks the public GitHub, Cloudflare, and npm status pages every two minutes. It saves what each source said, when it said it, and a fingerprint that helps show the record was not quietly replaced.</p></div></article><article><b>03</b><div><h2>What happens when I click “Investigate”?</h2><p>The live signal becomes a saved case. The case keeps the original source, time, status, and history together, so another person can inspect the same evidence later.</p></div></article><article><b>04</b><div><h2>Why can’t every live case be proved immediately?</h2><p>Faultline should not change GitHub, Cloudflare, or npm to test a theory. A real causal test needs a safe copy of the affected system, plus a clear list of changes the system is allowed to try. Without those, Faultline saves the evidence and says “not proven yet.”</p></div></article><article><b>05</b><div><h2>What is the Counterfactual Lab?</h2><p>It contains twelve fixed practice incidents. Because they are controlled test cases, Faultline can replay a failure, change one thing, and check whether the failure disappears without risking a real service.</p></div></article><article><b>06</b><div><h2>When does Faultline call something the cause?</h2><p>Only when changing the suspected cause clears the original failure, makes the system healthier, and does not create another problem.</p></div></article><article><b>07</b><div><h2>Does it repair production by itself?</h2><p>No. This version does not make changes to a real production system. Important actions are limited to an approved list, tested safely, and left for a person to approve.</p></div></article><article><b>08</b><div><h2>What does the 100% result mean?</h2><p>Faultline solved all twelve fixed test incidents. The simple baseline solved four. That shows a clear improvement on this controlled set. It does not mean Faultline will be perfect on every real incident.</p></div></article></section>
    <div className="docs-actions"><Link href="/dashboard">See the system live</Link><Link href="/evidence">Inspect the evidence</Link><a href="https://github.com/XaidenLabs/faultline-incident-os" target="_blank" rel="noreferrer">Open the code</a></div>
  </main>;
}
